### ISSUE TITLE
Noises are added to the actions?

### ISSUE THREAD

**Issue by MohammadAsadolahi** [BolunDai0216/DeepReinforcementLearning#1]
Hi and thank you for sharing such a project
I wonder what do you mean by saying "Noises are added to the actions"
do you mean you have added noise to actions only with sigma produced by actor net or you have added extra noise in addition?

**Comment by BolunDai0216** [comment]
> Hi and thank you for sharing such a project
> I wonder what do you mean by saying "Noises are added to the actions"
> do you mean you have added noise to actions only with sigma produced by actor net or you have added extra noise in addition?

I assume you are referring to the SAC implementation?

I was talking about the noise added [here](https://github.com/BolunDai0216/DeepReinforcementLearning/blob/aa72fc511b972fe629003f559ba3c2748cb4014e/HW3/sac_model.py#L159). The sigma produced by the actor net is used for the "reparameterization trick", which replaces sampling.

**Comment by MohammadAsadolahi** [comment]
Thank you for answering.
As i can see in:
action += self.act_noise * (-2 * np.random.random(4) + 1)
You have added noise to action by  a constant "self.act_noise" which you dont train so its like adding noise to every action like DDPG or TD3
Am i right?

**Comment by BolunDai0216** [comment]
> Thank you for answering. As i can see in: action += self.act_noise * (-2 * np.random.random(4) + 1) You have added noise to action by a constant "self.act_noise" which you dont train so its like adding noise to every action like DDPG or TD3 Am i right?

Yes, exactly.
